### ISSUE TITLE
Unable to load SpaceVim due to Vim 8 syntax errors 

### ISSUE THREAD

**Issue by jetm** [wsdjeg/SpaceVim#1688]
Executing latest Vim 8 (8.0.1783) version with the most recent SpaceVim commit this error appears:
```
Error detected while processing $HOME/.SpaceVim/config/main.vim:
line   10:
E116: Invalid arguments for function fnamemodify(expand('<sfile>'),
E15: Invalid expression: fnamemodify(expand('<sfile>'),
line   11:
E10: \ should be followed by /, ? or &
line   12:
E10: \ should be followed by /, ? or &
line   18:
E121: Undefined variable: g:_spacevim_root_dir
E116: Invalid arguments for function fnamemodify(g:_spacevim_root_dir, ':p:h:h')
E15: Invalid expression: 'set rtp +=' . fnamemodify(g:_spacevim_root_dir, ':p:h:h')
Error detected while processing /users/tiamarin/.SpaceVim/vimrc:
line   11:
E171: Missing :endif
```

## Expected behavior, English is required

SpaceVim should load without issues.

## The reproduce ways from Vim starting (Required!)

Install Vim in Ubuntu from Jonathon PPA:
```
sudo add-apt-repository ppa:jonathonf/vim
sudo apt-get update
```

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

Unable to post the debug info because SpaceVim is not loaded.

**Comment by jetm** [comment]
I traced back Vim versions and 8.0.1737 works fine. So, a temporal fix in Ubuntu is to hold the packages to that version. But, I am afraid later someone else will find this issue as well.

**Comment by wsdjeg** [comment]
It should be fixed, please update spacevim.

**Comment by jetm** [comment]
That fixed it. Thanks!

**Comment by fanchunke** [comment]
same issue in vim 8.0.1802

**Comment by jetm** [comment]
@wsdjeg: the issue is back with vim 8.0.1802, as @fanchunke1991 mentioned it.

The new error:
```
Error detected while processing /users/tiamarin/.SpaceVim/config/main.vim:
line   16:
E116: Invalid arguments for function fnamemodify(expand('<sfile>'),
E15: Invalid expression: fnamemodify(expand('<sfile>'),
line   17:
E10: \ should be followed by /, ? or &
line   18:
E10: \ should be followed by /, ? or &
line   24:
E121: Undefined variable: g:_spacevim_root_dir
E116: Invalid arguments for function fnamemodify(g:_spacevim_root_dir, ':p:h:h')
E15: Invalid expression: 'set rtp +=' . fnamemodify(g:_spacevim_root_dir, ':p:h:h')
Error detected while processing /users/tiamarin/.SpaceVim/vimrc:
line   11:
E171: Missing :endif
```

**Comment by jetm** [comment]
A workaround is `set nocompatible` in line 15 of `config/main.vim` file.
