### ISSUE TITLE
spacevim command completion not helpful and (apparently) no way to fix

### ISSUE THREAD

**Issue by Jemi** [wsdjeg/SpaceVim#3414]
Bringing up command-line with ':' and then typing a partial command followed by `<tab>` results in unhelpful behavior. The `<tab>` autocompletes to the first suggestion in the completion list, thus forcing the user to `<tab>,<tab>,<tab>...` until they get to the completion they want. This is usually almost as difficult as laboriously typing the command in the first place would have been. It could occasionally be even more difficult as a matter of fact. The documentation describes auto_completion_tab_key_behavior = "cycle" should result in a completion of the common substring and then the option to either keep typing or use `<tab>` as desired. Unfortunately, setting that option seems to have no effect on the commandline completion behavior.

 
## Expected behavior, english is required
In command-line mode, the `<tab>` key should autocomplete based on the 'common prefix' as described on this line:
"cycle completes the common prefix and cycle between candidates" on this page of the documentation: https://spacevim.org/layers/autocomplete/. The behavior described on that line should be the default behavior.

## The reproduce ways from Vim starting (Required!)
Start spacevim. type `:h<tab>`. Observe that it completes to the first available candidate - and this is in no way a sensible default.

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.
SpaceVim layers:

- VersionControl:       not loaded          no exists
+ autocomplete:             loaded          no exists
- chat:                 not loaded          no exists
+ checkers:                 loaded          no exists
- chinese:              not loaded          no exists
+ colorscheme:              loaded          no exists
+ core#banner:              loaded          no exists
+ core#statusline:          loaded          no exists
+ core#tabline:             loaded          no exists
+ core:                     loaded          no exists
- cscope:               not loaded          no exists
- ctrlp:                not loaded          no exists
- ctrlspace:            not loaded          no exists
- debug:                not loaded          no exists
- denite:               not loaded          no exists
+ edit:                     loaded          no exists
- exprfold:             not loaded          no exists
- floobits:             not loaded          no exists
+ format:                   loaded          no exists
- fuzzy:                not loaded          no exists
+ fzf:                      loaded          no exists
- games:                not loaded          no exists
- git:                  not loaded          no exists
- github:               not loaded          no exists
- gtags:                not loaded          no exists
- incsearch:            not loaded          no exists
- indentmove:           not loaded          no exists
- japanese:             not loaded          no exists
- lang#WebAssembly:     not loaded          no exists
- lang#agda:            not loaded          no exists
- lang#asciidoc:        not loaded          no exists
- lang#aspectj:         not loaded          no exists
- lang#assembly:        not loaded          no exists
- lang#autohotkey:      not loaded          no exists
- lang#batch:           not loaded          no exists
- lang#c:               not loaded          no exists
- lang#chapel:          not loaded          no exists
- lang#clojure:         not loaded          no exists
- lang#coffeescript:    not loaded          no exists
- lang#crystal:         not loaded          no exists
- lang#csharp:          not loaded          no exists
- lang#d:               not loaded          no exists
- lang#dart:            not loaded          no exists
- lang#dockerfile:      not loaded          no exists
- lang#elixir:          not loaded          no exists
- lang#elm:             not loaded          no exists
- lang#erlang:          not loaded          no exists
- lang#extra:           not loaded          no exists
- lang#foxpro:          not loaded          no exists
- lang#fsharp:          not loaded          no exists
- lang#go:              not loaded          no exists
- lang#goby:            not loaded          no exists
- lang#gosu:            not loaded          no exists
- lang#graphql:         not loaded          no exists
- lang#groovy:          not loaded          no exists
- lang#hack:            not loaded          no exists
- lang#haskell:         not loaded          no exists
- lang#html:            not loaded          no exists
- lang#hy:              not loaded          no exists
- lang#idris:           not loaded          no exists
- lang#io:              not loaded          no exists
- lang#ipynb:           not loaded          no exists
- lang#j:               not loaded          no exists
- lang#janet:           not loaded          no exists
- lang#java:            not loaded          no exists
- lang#javascript:      not loaded          no exists
- lang#json:            not loaded          no exists
- lang#julia:           not loaded          no exists
- lang#kotlin:          not loaded          no exists
- lang#lasso:           not loaded          no exists
- lang#latex:           not loaded          no exists
- lang#lisp:            not loaded          no exists
- lang#livescript:      not loaded          no exists
- lang#lua:             not loaded          no exists
- lang#markdown:        not loaded          no exists
- lang#matlab:          not loaded          no exists
- lang#nim:             not loaded          no exists
- lang#nix:             not loaded          no exists
- lang#ocaml:           not loaded          no exists
- lang#pact:            not loaded          no exists
- lang#pascal:          not loaded          no exists
- lang#perl:            not loaded          no exists
- lang#php:             not loaded          no exists
- lang#plantuml:        not loaded          no exists
- lang#pony:            not loaded          no exists
- lang#powershell:      not loaded          no exists
- lang#processing:      not loaded          no exists
- lang#prolog:          not loaded          no exists
- lang#puppet:          not loaded          no exists
- lang#purescript:      not loaded          no exists
- lang#python:          not loaded          no exists
- lang#r:               not loaded          no exists
- lang#racket:          not loaded          no exists
- lang#red:             not loaded          no exists
- lang#ring:            not loaded          no exists
- lang#ruby:            not loaded          no exists
- lang#rust:            not loaded          no exists
- lang#scala:           not loaded          no exists
- lang#scheme:          not loaded          no exists
- lang#sh:              not loaded          no exists
- lang#slim:            not loaded          no exists
- lang#solidity:        not loaded          no exists
- lang#sql:             not loaded          no exists
- lang#swift:           not loaded          no exists
- lang#swig:            not loaded          no exists
- lang#tcl:             not loaded          no exists
- lang#toml:            not loaded          no exists
- lang#typescript:      not loaded          no exists
- lang#v:               not loaded          no exists
- lang#vbnet:           not loaded          no exists
- lang#vim:             not loaded          no exists
- lang#vue:             not loaded          no exists
- lang#wdl:             not loaded          no exists
- lang#wolfram:         not loaded          no exists
- lang#xml:             not loaded          no exists
- lang#xquery:          not loaded          no exists
- lang#zig:             not loaded          no exists
- leaderf:              not loaded          no exists
- lsp:                  not loaded          no exists
- mail:                 not loaded          no exists
- operator:             not loaded          no exists
- org:                  not loaded          no exists
+ shell:                    loaded          no exists
- sudo:                 not loaded          no exists
- test:                 not loaded          no exists
- tmux:                 not loaded          no exists
- tools#dash:           not loaded          no exists
- tools#mpv:            not loaded          no exists
- tools#screensaver:    not loaded          no exists
- tools#zeal:           not loaded          no exists
- tools:                not loaded          no exists
+ ui:                       loaded          no exists
- unite:                not loaded          no exists
- vim:                  not loaded          no exists

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
The option `auto_completion_tab_key_behavior` in autocomplete layer is only for insert mode, not for command line mode. in command line mode we do not change the key binding `<Tab>`

**Comment by Jemi** [comment]
Some documentation maybe on what `<tab>` is doing in command-line mode? In standard vim with no plugins there's no (useless) fancy menu when you press tab. But there is a (useful) common substring completion behavior. So if you've taken something useful and replaced it with something useless, and on top of that there's not even documentation for what the useless feature is called, how it's implemented, how to replace/modify/augment it, etc, then this is a bug that creates a problem for users, and should be fixed.

**Comment by wsdjeg** [comment]
@Jemi I still do not understand what is the feature you want.

**Comment by Jemi** [comment]
Document what ```<tab>``` does in command-line mode, so that the problem can be discussed properly. The normal ```<tab>``` behavior in command-line mode has been replaced, but I wasn't able to find any documentation on what has replaced it. Common substring completion should be the sensible default, instead  of tab cycling through a list of completions.

**Comment by wsdjeg** [comment]
We do not change the behavior of `<Tab>` in command line mode, `:cmap <tab>` shows `no mapping found`.

**Comment by Jemi** [comment]
I haven't used spacevim in months, so it's possible something may have changed. Does ```<tab>``` in command line mode result in common substring completion for you?

**Comment by wsdjeg** [comment]
Yeah, we do not change the behavior of `Tab` in command line mode.

**Comment by BryanDonovan** [comment]
I believe this is actually a difference between Neovim and regular vim, so it might depend on which type of vim you were using with SpaceVim.
