### ISSUE TITLE
LaTex error shows in the quick fix that prompt out but not in the vimtex-errors.

### ISSUE THREAD

**Issue by ChasingZenith** [wsdjeg/SpaceVim#3470]
## Expected behavior, English is required

I am trying writing LaTex with SpaceVim. I added the option `lang#latex` in init.toml and SpaceVim automatically installed Vimtex. But when I compiled it. A quickfix buffer shows up and gives tons of LaTex error. The LaTex file can be compiled without any error, I checked it with VSCode.(Previously I use VSCode to edit LaTex and compile LaTex with TeXlive suite).

![Untitled 2](https://user-images.githubusercontent.com/22112456/80055672-d4134080-8554-11ea-8cc6-6c8ec9380999.png)

![Untitled](https://user-images.githubusercontent.com/22112456/80052558-8941fa80-854d-11ea-986b-528886b3e99c.png)

How can I get rig of this annoying 'fake' error?

More interestingly, when I use `SPC l e` to see vimtex-errors, another quickfix buffer came out. And this time the information is correct and which is exactly the same information as I compile it with VSCode. 

![Untitled](https://user-images.githubusercontent.com/22112456/80052631-b68ea880-854d-11ea-81b2-f380dbeb7cb2.png)

I find that the wrong error information are all given by `lacheck`. And I search a lot in the previous issues and find that this problem also involves neomake. And have something to do with so call location
 

## The reproduce ways from Vim starting (Required!)

I add the following vim file in `.SpaceVim.d/autoload/latexconfig.vim`

<details><summary> latexconfig.vim </summary>

function! latexconfig#before() abort
let g:tex_flavor='latex'
let g:vimtex_latexmk_options='-syntex=1 -interaction=nonstopmode -file-line-error -pdf '
" let g:vimtex_view_general_viewer = 'evince'
let g:vimtex_quickfix_mode=0
" let g:neomake_open_list = 0
let g:indentLine_fileTypeExclude = ['latex', 'tex', 'markdown']
let g:indentLine_enabled=0
au Filetype tex setlocal conceallevel=1
au Filetype tex IndentLinesDisable
au Filetype tex let g:indentLine_setColors=0
au Filetype tex colorscheme gruvbox
let g:tex_conceal='abdmgs'
setlocal spell
set spelllang=en_us
inoremap <C-l> <c-g>u<Esc>[s1z=`]a<c-g>u
endfunction

</details>

In my init.toml, I add the following int the `[option]`
```
    bootstrap_before = "latexconfig#before"
    snippet_engine = "ultisnips"
    disabled_plugins=["intendedlines"]
```
And add 
```
[[layers]]
name = 'lang#latex'

[[custom_plugins]]
name = "KeitaNakamura/tex-conceal.vim"
merged = false
```
There are two tex file, please save this two tex file in the same folder

<details><summary> main.tex </summary>

%!TEX program=xelatex
\documentclass[10pt]{article}
%\usepackage[shortlabels]{enumitem}
\usepackage[a4paper]{geometry}
\usepackage{upquote}
\usepackage{float}
\usepackage{pdfpages}

\geometry{verbose,tmargin=2cm,bmargin=2cm,lmargin=2cm,rmargin=2cm}
\geometry{verbose,tmargin=2cm,bmargin=2cm,lmargin=2cm,rmargin=2cm}
% For whom 
\input{defs.tex}

\begin{document}
\author{XX}
\date{Due on April 20, 2020, 23:59 UTC+8}
\title{ Spring 2020 \\
	Homework 3}
\maketitle

hello world
\end{document}

</details>

<details><summary> defs.tex </summary>

\newcommand{\ones}{\mathbf 1}
\newcommand{\reals}{{\mbox{\bf R}}}
\newcommand{\integers}{{\mbox{\bf Z}}}
\newcommand{\symm}{{\mbox{\bf S}}}  % symmetric matrices

\newcommand{\nullspace}{{\mathcal N}}
\newcommand{\range}{{\mathcal R}}
\newcommand{\Rank}{\mathop{\bf Rank}}
\newcommand{\Tr}{\mathop{\bf Tr}}
\newcommand{\diag}{\mathop{\bf diag}}
\newcommand{\card}{\mathop{\bf card}}
\newcommand{\SNR}{\textrm{SNR}}
\newcommand{\rank}{\mathop{\bf rank}}
\newcommand{\conv}{\mathop{\bf conv}}
\newcommand{\prox}{\mathbf{prox}}

\newcommand{\Expect}{\mathbb{E}{}}
\newcommand{\Prob}{\mathop{\bf Prob}}
\newcommand{\Co}{{\mathop {\bf Co}}} % convex hull
\newcommand{\dist}{\mathop{\bf dist{}}}
\newcommand{\argmin}{\mathop{\rm argmin}}
\newcommand{\argmax}{\mathop{\rm argmax}}
\newcommand{\epi}{\mathop{\bf epi}} % epigraph
\newcommand{\Vol}{\mathop{\bf vol}}
\newcommand{\dom}{\mathop{\bf dom}} % domain
\newcommand{\intr}{\mathop{\bf int}}
\newcommand{\sign}{\mathop{\bf sign}}
\newcommand{\mysign}[1]{\mathop{\rm{#1}}}
\newcommand{\question}[1]{{\color{red}{#1}}}

\newcommand{\cf}{{\it cf.}}
\newcommand{\eg}{{\it e.g.}}
\newcommand{\ie}{{\it i.e.}}
\newcommand{\etc}{{\it etc.}}

\definecolor{color1}{HTML}{D0B22B}
\definecolor{dred}{RGB}{128,0,0}
\definecolor{colorhkust}{RGB}{20,43,140}
\definecolor{colorshanghaitech}{RGB}{162,0,5}
\definecolor{colortsinghua}{RGB}{116,52,129}
\definecolor{colorpink}{RGB}{255,204,204}
\definecolor{colororange}{RGB}{255,153,102}
\definecolor{header1}{cmyk}{0.9,0.5,0,0.35}

</details>

Then enter the folder. run `vim main.tex`, save the file with `:w`, vimtex compiles and give a quickfix.
After that `SPC l e` gives another one
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.
## Environment Information

- OS: linux
- vim version: 8.1(1-875, 878, 884, 948, 1046, 1365-1368, 1382, 1401)
- neovim version: -
- SpaceVim version: 1.5.0-dev
- SpaceVim status:

```
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	UltiSnips/

nothing added to commit but untracked files present (use "git add" to track)
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

``toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_before = 'latexconfig#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['KeitaNakamura/tex-conceal.vim', {'name': 'KeitaNakamura/tex-conceal.vim', 'merged': 0}]]
  data_dir = '/home/dial-dengzhch/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = ['intendedlines']
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/dial-dengzhch/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vimtex'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'ultisnips'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.5.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```


### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#latex"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim.gtk)
version: 801
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [09:55:19] [ Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [09:55:19] [ Info ] find local conf: /home/dial-dengzhch/.SpaceVim.d/init.toml
[ SpaceVim ] [09:55:19] [ Info ] generate local conf: /home/dial-dengzhch/.cache//SpaceVim/conf/_home_dial-dengzhch__SpaceVim_d_init_toml.json
[ SpaceVim ] [09:55:19] [ Info ] start to apply config [local]
[ SpaceVim ] [09:55:19] [ Info ] Start to find root for: /home/dial-dengzhch/
[ SpaceVim ] [09:55:19] [ Info ]         (.SpaceVim.d/):/home/dial-dengzhch
[ SpaceVim ] [09:55:19] [ Info ] buffer name:
[ SpaceVim ] [09:55:19] [ Info ] change to root: /home/dial-dengzhch
[ SpaceVim ] [09:55:19] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [09:55:19] [ Info ] buffer name:
[ SpaceVim ] [09:55:19] [ Info ] change to root: /home/dial-dengzhch
[ SpaceVim ] [09:55:22] [ Info ] Start to find root for: /home/dial-dengzhch/Desktop/CVX2020HW3/main.tex
[ SpaceVim ] [09:55:22] [ Info ]         (.SpaceVim.d/):/home/dial-dengzhch
[ SpaceVim ] [09:55:22] [ Info ] buffer name: /home/dial-dengzhch/Desktop/CVX2020HW3/main.tex
[ SpaceVim ] [09:55:22] [ Info ] change to root: /home/dial-dengzhch
[ SpaceVim ] [09:55:32] [ Info ] Start to find root for: /home/dial-dengzhch/.SpaceVim.d/init.toml
[ SpaceVim ] [09:55:32] [ Info ]         (.SpaceVim.d/):/home/dial-dengzhch
[ SpaceVim ] [09:55:32] [ Info ] buffer name: /home/dial-dengzhch/.SpaceVim.d/init.toml
[ SpaceVim ] [09:55:32] [ Info ] change to root: /home/dial-dengzhch
[ SpaceVim ] [09:57:19] [ Info ] buffer name: Desktop/CVX2020HW3/main.tex
[ SpaceVim ] [09:57:19] [ Info ] change to root: /home/dial-dengzhch
[ SpaceVim ] [09:57:22] [ Info ] Start to find root for: /home/dial-dengzhch/Desktop/CVX2020HW3/main.tex
[ SpaceVim ] [09:57:22] [ Info ]         (.SpaceVim.d/):/home/dial-dengzhch
[ SpaceVim ] [09:57:22] [ Info ] buffer name: Desktop/CVX2020HW3/main.tex
[ SpaceVim ] [09:57:22] [ Info ] change to root: /home/dial-dengzhch
[ SpaceVim ] [09:57:30] [ Info ] Start to find root for: /tmp/v6RlEwk/4/issue_report.md
[ SpaceVim ] [09:57:30] [ Info ] buffer name: /tmp/v6RlEwk/4/issue_report.md
[ SpaceVim ] [09:57:30] [ Info ] change to root: /home/dial-dengzhch
```
</details>

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
@ChasingZenith This should be fixed in master

**Comment by ChasingZenith** [comment]
> @ChasingZenith This should be fixed in master

Thank you for your reply.

But sorry, please forgive me that I can't fully understand this sentence. Has it been fixed in master? Or is the work still in progress?

I tried `git -C ~/.SpaceVim pull` to got SpaceVim up to date just now. But the issue still remained. I don't know if I have done it in the wrong way.

**Comment by wsdjeg** [comment]
I have update spacevim statusline in #3653, the location list is opened by neomake, you can disable all latex maker via:

```
let g:neomake_enabled_tex_makers = []
```
