### ISSUE TITLE
Wrong configuration file directory.

### ISSUE THREAD

**Issue by abc123098123** [wsdjeg/SpaceVim#4090]
## Expected behavior, english is required

There should be a file called `init.toml` inside `~/.SpaceVim.d` that should be used for configurations.
Configuration directory should be `~/.SpaceVim.d`.

## The reproduce ways from Vim starting (Required!)

Install latest version (`1.7.0-dev`).

There won't be any `init.toml` inside `~/.SpaceVim.d`. Instead, there is this file: `~/.SpaceVim.dinit.toml`.
The configuration directory is `~/.SpaceVim` instead of `~/.SpaceVim.d`.

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

!-- please remove the issue template when request for a feature -->
# Expected behavior, english is recommend

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.4.4
- SpaceVim version: 1.7.0-dev
- SpaceVim status: a34c156f

```
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   autoload/SpaceVim.vim

no changes added to commit (use "git add" and/or "git commit -a")
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  automatic_update = 0
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/romeu/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 4
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 0
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/romeu/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'rust.vim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'Cargo.toml', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'bar'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode_symbols = 0
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.7.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="fzf"
[[layers]]
  name="git"
[[layers]]
  name="VersionControl"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#rust"
[[layers]]
  name="lsp"
  override_cmd={'rust': ['rust-analyzer']}
  filetypes=['rust']
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [18:58:34] [ Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [18:58:34] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [18:58:34] [ Info ] global_dir is: /home/romeu/.SpaceVim.d
[ SpaceVim ] [18:58:34] [ Info ] start to apply config [glob]
[ SpaceVim ] [18:58:34] [ Error ] failed to call bootstrap_before function: myspacevim#before
[ SpaceVim ] [18:58:34] [ Error ]        exception: Vim(call):E117: Unknown function: myspacevim#before
[ SpaceVim ] [18:58:34] [ Error ]        throwpoint: function SpaceVim#custom#load[34]..<SNR>50_load_glob_conf[14]..SpaceVim#custom#apply, line 54
[ SpaceVim ] [18:58:34] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [18:58:34] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [18:58:34] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [18:58:34] [ Info ] try to open SpaceVim welcome page
[   rooter ] [18:58:35] [ Info ] Load projects cache from: /home/romeu/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:58:35] [ Error ] failed to call bootstrap_after function: myspacevim#after
[ SpaceVim ] [18:58:35] [ Error ]        exception: Vim(call):E117: Unknown function: myspacevim#after
[ SpaceVim ] [18:58:35] [ Error ]        throwpoint: function SpaceVim#autocmds#VimEnter, line 34
[   rooter ] [18:58:37] [ Info ] Start to find root for: /home/romeu/SpaceVimLayers
[   rooter ] [18:58:37] [ Info ] buffer name: SpaceVimLayers
[   rooter ] [18:58:37] [ Info ] same as current directory, no need to change.
[   rooter ] [18:58:42] [ Info ] Start to find root for: /home/romeu/
[   rooter ] [18:58:42] [ Info ] buffer name: No Name
[   rooter ] [18:58:42] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [18:58:46] [ Info ] key binding guide float statusline winid:1005
[   rooter ] [18:58:47] [ Info ] buffer name: No Name
[   rooter ] [18:58:47] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [18:58:47] [ Info ] close float statusline winid:1005
[ SpaceVim ] [18:58:47] [ Info ] key binding guide float statusline winid:1007
[   rooter ] [18:58:47] [ Info ] buffer name: No Name
[   rooter ] [18:58:47] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [18:58:47] [ Info ] close float statusline winid:1007
[   rooter ] [18:58:47] [ Info ] Start to find root for: /tmp/nvimZw9H5e/1/issue_report.md
[   rooter ] [18:58:47] [ Info ] buffer name: /tmp/nvimZw9H5e/1/issue_report.md
[   rooter ] [18:58:47] [ Info ] same as current directory, no need to change.
```
</details>

## Screenshots

None

**Comment by wsdjeg** [comment]
421c059d should fix this issue, I can not reproduce it now.

**Comment by wsdjeg** [comment]
I have checked the runtime log:

```
[ SpaceVim ] [18:58:34] [ Info ] global_dir is: /home/romeu/.SpaceVim.d
```

I think it should be:

```
[ SpaceVim ] [18:58:34] [ Info ] global_dir is: /home/romeu/.SpaceVim.d/
```

**Comment by abc123098123** [comment]
Well sure, but the script is installing SpaceVim in `~/.SpaceVim`, not `~/.SpaceVim.d`. 
Is this intentional?

**Comment by wsdjeg** [comment]
Yeah, `~/.SpaceVim` is the main repo of SpaceVim, and file in this directory should not be changed.

**Comment by abc123098123** [comment]
Ok I understad now. But regardless, I tried to use the install script today, the problem persists. The commit you did reference didn't fix anything.

**Comment by wsdjeg** [comment]
@RomeuG Can you test #4200, I have added many log info, can you test it, and post the debug info.
