### ISSUE TITLE
typescript-language-server seem not working

### ISSUE THREAD

**Issue by kavience** [wsdjeg/SpaceVim#4497]
I am a beginner at vim and SpaceVim,  I am trying to config lsp for typescript and javascript,  but things seem not smooth, here is my configuration. 

```
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#typescript"
# enable = false

[[layers]]
name = "lsp"
filetypes = [
  "javascript",
  "javascriptreact",
  "typescript",
  "typescriptreact"
]


```

and `:SPDebugInfo` looks like :

<img width="1440" alt="1" src="https://user-images.githubusercontent.com/30547306/137596854-a7ba7f08-95f9-49f7-91d9-b529505f9fe6.png">

It makes me confuse , if I don't config lsp layer things seem to look right but it use `nvim_typescript` instead of `typescript-language-server`.

```
# comment these lines
# [[layers]]
# name = "lsp"
# filetypes = [
#   "javascript",
#   "javascriptreact",
#   "typescript",
#   "typescriptreact"
# ]
```
when I disabled lsp layers and open `.ts` file, SpaceVim autoload  `nvim_typescript`.
```
remote/host: node host registered plugins ['nvim_typescript']
remote/host: python3 host registered plugins []
```

is this normal or something error? 

Thinks!

**Comment by wsdjeg** [comment]
What is your vim version? please follow the issue template.

**Comment by kavience** [comment]
@wsdjeg 
NVIM v0.6.0-dev+254-g413e86869

I am using neovim

**Comment by kavience** [comment]
I found when I type`:LspInfo`, there is 0 client(s) attached to this buffer
![1](https://user-images.githubusercontent.com/30547306/137718722-273a9a58-fc26-4de4-a181-8bb7ca5f6f3a.png)

**Comment by ghost** [comment]
Same here, but for C++/clangd.
Autocompletion and "go to definition" don't work, although LSP is configured and clangd is installed 

checkhealth:
```

denite: health#denite#check
========================================================================
## denite.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful

lspconfig: require("lspconfig.health").check()
========================================================================
  - ERROR: Failed to run healthcheck for "lspconfig" plugin. Exception:
    function health#check, line 24
    Vim(eval):E5108: Error executing lua [string "luaeval()"]:1: attempt to call field 'check' (a nil value)

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='6402'
  - INFO: $COLORTERM='truecolor'

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python is Python 3.9 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Python version: 3.9.7
  - INFO: pynvim version: 0.4.2 (outdated; from /usr/lib/python3/dist-packages/neovim)
  - WARNING: Latest pynvim is NOT installed: 0.4.3

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-gnu]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v12.22.5
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /home/user/.cache/nvim/lsp.log
  - INFO: Log size: 1 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 13

```

nvim version:
```
user@dell-g5:~/gits/game$ nvim --version
NVIM v0.6.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -ffile-prefix-map=/build/neovim-zZpdQX/neovim-0.6.0~ubuntu1+git202111041211-f26b39131-adeb5640f=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-zZpdQX/neovim-0.6.0~ubuntu1+git202111041211-f26b39131-adeb5640f/build/config -I/build/neovim-zZpdQX/neovim-0.6.0~ubuntu1+git202111041211-f26b39131-adeb5640f/src -I/build/neovim-zZpdQX/neovim-0.6.0~ubuntu1+git202111041211-f26b39131-adeb5640f/.deps/usr/include -I/usr/include -I/build/neovim-zZpdQX/neovim-0.6.0~ubuntu1+git202111041211-f26b39131-adeb5640f/build/src/nvim/auto -I/build/neovim-zZpdQX/neovim-0.6.0~ubuntu1+git202111041211-f26b39131-adeb5640f/build/include
Compiled by buildd@lgw01-amd64-018

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

```

clangd:
```
user@dell-g5:~/gits/game$ clangd --version
Ubuntu clangd version 13.0.0-2
Features: linux
Platform: x86_64-pc-linux-gnu

```

config:
```
#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    enable_guicolors = false
    vimcompatible = false
    lint_engine = ""
    bootstrap_before = 'myspacevim#before'
    default_indent = 4
    expand_tab = true
    file_searching_tools = ['find', 'find -not -iwholename "*.git*" ', 'find -not -iwholename "*.git*" -name ']
    project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '!build/']

[[layers]]
name = 'core'
filetree_show_hidden = true
enable_smooth_scrolling = false

# Enable autocomplete layer
[[layers]]
name = "autocomplete"
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "cycle"

[[layers]]
  name="lang#c"
  enable_clang_syntax_highlight = true

[[layers]]
  name = "lsp"
  filetypes = [
    "c",
    "cpp"
  ]
  [layers.override_cmd]
    c = ["clangd"]
    cpp = ["clangd"]

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "denite"

[[layers]]
name = "format"
format_on_save = true

[[custom_plugins]]
repo = "Shougo/vimproc.vim"
build = "make"
merged = false

```

**Comment by programmador** [comment]
Guys, smth is really extremely wrong with LSP (maybe exactly coc-lsp) quite a long time already and I have no idea how to debug it at all.
First of all - intelephense (php) does not work at all as I wrote in #4501
Today I've tried to check whether LSP works for Rust. The answer is "not exactly".
1. It does check the file while saving but does not perform any checks ondemand while editing.
2. Renaming does not work. It just asks for new item name and does nothing on "enter".
Of course I also don't see any significant LSP activity via top/htop.

Here's an ondemand behaviour when I put my old archived .SpaceVim backup:
![screenshot_2021-12-18-205701](https://user-images.githubusercontent.com/674995/146652971-b93882e8-b4f8-4f8b-a298-57f55c797e6c.png)
So it was implemented and it was working. Just after performing `SPUpdate` this behaviour just disappears (as well as for other languages, for example PHP and seems like TypeScript is also affected though I didn't check).

And here's what am I expecting while renaming:
![screenshot_2021-12-18-205842](https://user-images.githubusercontent.com/674995/146653026-d7a56785-714d-46bb-bae2-dc8119862de0.png)
After updating via `SPUpdate` this dialog is not being shown anymore

There are no errors warnings or notices at all in :SPDebugInfo!. **I have no idea how to determine what's wrong with it. Nothing seems crashing**, it looks rather as deimplemented somehow.

And one more thing: Go is not affected. golsp works pervectly ondemand, rename is working, and I see golsp in htop.

**Comment by programmador** [comment]
I also do not have this
```
ERROR: Failed to run healthcheck for "lspconfig" plugin. Exception:
```
as @0xBYTESHIFT has with clangd. My log is clean with both Rust and PHP.

In updated (broken) SpaceVim `:LspInfo!` shows me zero clients attached - same as @kavience mentioned above.
As for an old (working) SpaceVim - it does not have this command at all.

It makes me think that some time ago either a refactoring or a new functionality set arrived into SpaceVim which broke many things from old functionality.

From what I could suggest:
* Maybe autocomplete_method="coc" setting does not work anymore, some other kind is used instead
* LSP layer is re-implemented from scratch and does not implement some old functionality
* Refactoring (or new functionality) just broke or disabled some of the old stuff

It would be helpful just to direct us where to find the misbehaviour cause. The most difficult thing with this issue is that the logs in most cases are clear of errors as I mentioned earlier.

**Comment by programmador** [comment]
For anyone having similar issues with neovim - please look first at #4501 - there is an explanation how to configure the built-in lsp using identifiers from [nvim-lspconfig doc](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md). As for me - everything is fixed for PHP, Rust, Go. Should fix other languages as well.

Originally this issue was for typescript and there were issues also with clangd, so the lsp config should probably be supplemented with a fragment like this:
```
...
[[layers]]
    name = 'lsp'
    enabled_clients = [
        'tsserver',
        'clangd'
    ]
    ...
...
```

**Comment by wsdjeg** [comment]
@programmador so this issue can be closed?

**Comment by programmador** [comment]
Looks like built-in language server is working for TypeScript as well as for other languages:
![screenshot_2022-02-02-095727](https://user-images.githubusercontent.com/674995/152115016-2af59150-7aef-48de-9f5f-8517f5664a29.png)
So probably the issue could be closed.

**Comment by ghost** [comment]
@programmador how does your rust configuration looks like?
mine is:
![image](https://user-images.githubusercontent.com/72412645/199844979-6caa8452-cf1e-4f35-bdeb-dde0f5853330.png)
and it still shows me 0 clients when I open *.rs files, although rust-analyzer is present in system, and I can freely launch it in shell.

**Comment by programmador** [comment]
@0xBYTESHIFT
```
...
[[layers]]
    name = "lsp"
    enabled_clients = [
        ...
        'rust_analyzer',
        ...
    ]
    filetypes = [
        ...
        "rust",
        ...
    ]
    [layers.override_client_cmds]
      ...
      rust_analyzer = ["rust-analyzer"]
      ...
...
[[layers]]
    name = "lang#rust"
...
```

This config is actual for neovim.

You can see [this google groups conversation](https://groups.google.com/g/spacevim/c/E5C9zXU_Xk8) for more info.
For vim (not neovim) probably config keys can differ a bit.
