### ISSUE TITLE
Startify fails to load splash screen on startup

### ISSUE THREAD

**Issue by ChuckIT** [wsdjeg/SpaceVim#4509]
## Expected behavior, english is recommend
When SpaceVim is started via "nvim" with no arguments SpaceVim should display the Startify screen and filemanager pane.

## Environment Information

- OS: linux (WSL)
- vim version: -
- neovim version: 0.4.3
- SpaceVim version: 1.9.0-dev
- SpaceVim status: 689fafcc

```
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   bundle/vim-toml

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    bundle/vim-toml

```

## The reproduce ways from Vim starting (Required!)
nvim <enter>

## Results
- Screen flashes Brad  Moolenar splash screen and immediately fills the window with the pane of a blank buffer. 
- No other panes present.

## Debug
- Upgraded all plugins and SpaceVim
- Commenting out all layers in init.toml results in the same issue
- Executing nvim with the same config in a termux window on Android 11  results in Startify screen being displayed properyly

## From investigations similar to this issue the following info was requested
:echo argc() = 0
:echo line2byte('$') = -1
echo v:servername = /tmp/nvimOKDzps/0
echo !argc() && (line2byte('$') == -1) ==> 1

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/chuck/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 1
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'defx'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/chuck/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'tern_for_vim'
  project_auto_root = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang', 'package.json']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.9.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="denite"
[[layers]]
  name="sudo"
[[layers]]
  name="git"
[[layers]]
  name="VersionControl"
[[layers]]
  name="lang#asciidoc"
[[layers]]
  name="lang#batch"
[[layers]]
  name="lang#html"
  user_emmet_leader_key='<C-e>'
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#toml"
[[layers]]
  name="lang#vbnet"
[[layers]]
  name="lang#json"
[[layers]]
  name="lang#xml"
[[layers]]
  name="lang#c"
[[layers]]
  name="lang#dockerfile"
[[layers]]
  name="tmux"
  tmux_navigator_modifier='alt'
[[layers]]
  name="lang#python"
  format_on_save=1
  enable_typeinfo=1
  enabled_linters=['python', 'pylint']
[[layers]]
  name="lang#javascript"
  format_on_save=1
  auto_fix=1
  enable_flow_syntax=1
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [22:35:07] [ Info ] Startup with argv: ['failed to get v:argv']
[ SpaceVim ] [22:35:07] [ Info ] find local conf: /home/chuck/.SpaceVim.d/init.toml
[ SpaceVim ] [22:35:07] [ Info ] loading cached local conf: /home/chuck/.cache/SpaceVim/conf/_home_chuck__SpaceVim_d_init_toml.json
[ SpaceVim ] [22:35:07] [ Info ] start to apply config [local]
[ SpaceVim ] [22:35:07] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [22:35:07] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [22:35:07] [ Info ] the func has been added to mode:paste-mode
[   rooter ] [22:35:07] [ Info ] Load projects cache from: /home/chuck/.cache/SpaceVim/projects.json
[   rooter ] [22:35:07] [ Info ] project_rooter_patterns option has been change, clear b:rootDir
[   rooter ] [22:35:07] [ Info ] Start to find root for: /home/chuck/
[   rooter ] [22:35:07] [ Info ] buffer name: No Name
[   rooter ] [22:35:07] [ Info ] same as current directory, no need to change.
[   rooter ] [22:35:07] [ Info ] buffer name: No Name
[   rooter ] [22:35:07] [ Info ] same as current directory, no need to change.
[   rooter ] [22:35:14] [ Info ] Start to find root for: /home/chuck/
[   rooter ] [22:35:14] [ Info ] buffer name: No Name
[   rooter ] [22:35:14] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [22:38:10] [ Info ] key binding guide float statusline winid:1004
[   rooter ] [22:38:10] [ Info ] buffer name: No Name
[   rooter ] [22:38:10] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [22:38:10] [ Info ] close float statusline winid:1004
[ SpaceVim ] [22:38:10] [ Info ] key binding guide float statusline winid:1006
[   rooter ] [22:38:11] [ Info ] buffer name: No Name
[   rooter ] [22:38:11] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [22:38:11] [ Info ] close float statusline winid:1006
[   rooter ] [22:38:11] [ Info ] Start to find root for: /tmp/nvim6hAJfd/1/issue_report.md
[   rooter ] [22:38:11] [ Info ] buffer name: /tmp/nvim6hAJfd/1/issue_report.md
[   rooter ] [22:38:11] [ Info ] same as current directory, no need to change.
```
</details>

**Comment by wsdjeg** [comment]
It seems a bug. I will test it.

**Comment by ChuckIT** [comment]
Few more thingsWSL Architecture Detail Wndows 10 21H2 running updated Ubuntu 20.04Did a complete uninstall and reinstall vanilla SpaceVim showed the same behavior.Thanks for looking into this.ChuckOn Nov. 3, 2021 05:52, Wang Shidong ***@***.***> wrote:
It seems a bug. I will test it.

**Comment by jesusangelm** [comment]
I have the same bug with neovim and Startify since about two weeks ago, after running an upgrade.

I remember that before they changed vimfiler to nerdtree, vimfiler was running automatically, but nerdtree is not doing it, I don't know if it is related to this change.

i tried uninstall and reinstall SpaceVim but without success.

with vim there seems to be no problems with Startify, but Nerdtree doesn't seem to run automatically as vimfiler did

**Comment by Djedouas** [comment]
same issue for me, with neovim and neovim-qt, ubuntu 21.04

**Comment by alexbarton** [comment]
Same here, but with "plain" vim 8.1 (Debian 10 package):
```
❯ vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 15 2019 16:41:15)
…
```

**Comment by TURING-V2** [comment]
same here on  nvim v0.4.4 , pop os

**Comment by ChuckIT** [comment]
Dont know if this will help but on the version of nvim listed below Startify displays normally. Nvim is running in termux on Android11 phone although it runs into the python3.10 issue. :(❯ nvim -vNVIM v0.5.1                                   Build type: Release                           LuaJIT 2.1.0-beta3Compilation: /home/builder/.termux-build/_cache/android-r21d-api-24-v5/bin/clang -fstack-protector-strong -Oz --target=aarch64-linux-android24 -I/data/data/com.termux/files/usr/include -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/builder/.termux-build/neovim/build/config -I/home/builder/.termux-build/neovim/src/src -I/data/data/com.termux/files/usr/include -I/home/builder/.termux-build/neovim/build/src/nvim/auto -I/home/builder/.termux-build/neovim/build/includeCompiled by ***@***.***: +acl +iconv +tuiSee ":help feature-compile"   system vimrc file: "$VIM/sysinit.vim"  fall-back for $VIM: "/data/data/com.termux/files/usr/share/nvim"On Nov. 3, 2021 08:56, Chuck ***@***.***> wrote:Few more thingsWSL Architecture Detail Wndows 10 21H2 running updated Ubuntu 20.04Did a complete uninstall and reinstall vanilla SpaceVim showed the same behavior.Thanks for looking into this.ChuckOn Nov. 3, 2021 05:52, Wang Shidong ***@***.***> wrote:
It seems a bug. I will test it.

**Comment by Djedouas** [comment]
On Ubuntu, I fixed it by updating neovim to 0.5.1 using [the PPA described in the installation wiki](https://github.com/neovim/neovim/wiki/Installing-Neovim#ubuntu)

**Comment by ChuckIT** [comment]
Yes adding the neovim ppa and upgrading to 0.5.1 solved the problem for me the standard ubuntu repositories only hand out 0.4.3.On Dec. 1, 2021 03:07, Djedouas ***@***.***> wrote:
On Ubuntu, I fixed it by updating neovim to 0.5.1 using the PPA described in the installation wiki

**Comment by wsdjeg** [comment]
please update neovim, because neovim data file format has been changed.

**Comment by Mick235711** [comment]
Still experiencing the exact same issue here on macOS + MacVim... Also have screen flashes Brad Moolenar splash screen and immediately fills the window with the pane of a blank buffer.
Version: macOS 10.15.7 + MacVim 8.2-172 (aka Vim 8.2.3455) + SpaceVim 1.9.0-687736f2
(+ NeoVim 0.6.1), two vim all installed from homebrew formula `neovim` and cask `macvim`.

On macOS, the implementation strategy is that there is a single binary `mvim` under `MacVim.app`, and this binary is then linked in `/usr/local/bin` several times under different names (`vim`, `gvim`, `mvim`, `vi`, etc.), and the binary will behave differently when called under different name.

The interesting behavior here is that any command line usage (`vim`, `vi`, and a separately installed `nvim`) will operate normally, but open in GUI mode (`gvim`, `mvim`, or directly open `MacVim.app`) will result in flash splash + blank buffer, though `vim` and `gvim` are same binary, apparently they are differently behaved.

Should I wait for some Vim updates too? (Cause I'm sure that splash screen is working in 1.8.0)

(Added debug information:
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'ycm'
  autocomplete_parens = 1
  background = 'dark'
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'onedark'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['wakatime/vim-wakatime'], ['rlue/vim-barbaric']]
  data_dir = '/Users/mick/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 4
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 1
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline = 1
  enable_statusline_bfpath = 0
  enable_statusline_display_mode = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 1
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = 'Mick235711'
  guifont = 'SauceCodePro Nerd Font:h14'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = 'en_US.UTF-8'
  layer_lang_java_formatter = '/Users/Mick/google-java-format.jar'
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 1
  max_column = 120
  plugin_bundle_dir = '/Users/mick/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'devdocs.vim'
  project_auto_root = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang', 'pom.xml']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 0
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'ultisnips'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.9.0'
  vim_help_language = 'cn'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```


### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='nil'
  enable=1
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
  lint_on_the_fly=1
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="chinese"
[[layers]]
  name="colorscheme"
[[layers]]
  name="debug"
[[layers]]
  name="default"
[[layers]]
  name="fzf"
[[layers]]
  name="git"
[[layers]]
  name="github"
[[layers]]
  name="lang#c"
  libclang_path='/usr/local/opt/llvm/lib'
  clang_executable='/usr/local/opt/llvm/bin/clang'
  enable_clang_syntax_highlight=1
  clang_flag=['-O2', '-std=c++17', '-Wall', '-Weverything']
[[layers]]
  name="lang#d"
[[layers]]
  name="lang#hack"
[[layers]]
  name="lang#matlab"
[[layers]]
  name="lang#pascal"
[[layers]]
  name="lang#prolog"
[[layers]]
  name="lang#powershell"
[[layers]]
  name="lang#sql"
[[layers]]
  name="lang#tcl"
[[layers]]
  name="lang#haskell"
[[layers]]
  name="lang#java"
[[layers]]
  name="lang#latex"
[[layers]]
  name="lang#lua"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#ruby"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lsp"
  override_cmd={'c': ['/usr/local/opt/llvm/bin/clangd'], 'cpp': ['/usr/local/opt/llvm/bin/clangd']}
  filetypes=['c', 'cpp', 'sh', 'python']
[[layers]]
  name="sudo"
[[layers]]
  name="test"
[[layers]]
  name="tmux"
[[layers]]
  name="tools"
[[layers]]
  name="tools#dash"
```


### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: Vim(/Applications/MacVim.app/Contents/MacOS/Vim)
version: 802
OS: mac
[shell, shellcmdflag, shellslash]: ['/usr/local/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [14:21:51] [0.001] [  Info ] start to loading SpaceVim!
[ SpaceVim ] [14:21:51] [0.001] [  Info ] init spacevim root dir:/Users/mick/.SpaceVim/
[ SpaceVim ] [14:21:51] [0.169] [  Info ] Startup with argv: ['/Applications/MacVim.app/Contents/MacOS/Vim', '-g', '-f']
[ SpaceVim ] [14:21:51] [0.192] [  Info ] find local conf: /Users/mick/.SpaceVim.d/init.toml
[ SpaceVim ] [14:21:51] [0.194] [  Info ] loading cached local conf: /Users/mick/.cache/SpaceVim/conf/_Users_mick__SpaceVim_d_init_toml.json
[ SpaceVim ] [14:21:51] [0.195] [  Info ] start to apply config [local]
[ SpaceVim ] [14:21:51] [0.220] [  Info ] before
[ SpaceVim ] [14:21:51] [0.225] [  Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[ SpaceVim ] [14:21:51] [0.278] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [14:21:51] [0.315] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [14:21:51] [0.315] [  Info ] the func has been added to mode:paste-mode
[   rooter ] [14:21:51] [0.380] [  Info ] Load projects cache from: /Users/mick/.cache/SpaceVim/projects.json
[ SpaceVim ] [14:21:52] [0.618] [  Info ] finished loading SpaceVim!
[   rooter ] [14:21:52] [1.051] [  Info ] project_rooter_patterns option has been change, clear b:rootDir
[   rooter ] [14:21:52] [1.052] [  Info ] Start to find root for: /Users/mick/
[   rooter ] [14:21:52] [1.054] [  Info ] buffer name: No Name
[   rooter ] [14:21:52] [1.054] [  Info ] same as current directory, no need to change.
[   rooter ] [14:21:52] [1.129] [  Info ] buffer name: No Name
[   rooter ] [14:21:52] [1.129] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [14:21:52] [1.198] [  Info ] after
```
</details>
)

**Comment by danchev** [comment]
I have the same problem with Startify, in addition to getting the following error.
![image](https://user-images.githubusercontent.com/12420863/148633181-e4507f62-29b0-44f9-8a3e-865a8724130c.png)

SpaceVim v1.9.0

NAME="openSUSE Tumbleweed"
VERSION="20220106"

VIM - Vi IMproved 8.2 (2019 Dec 12)
Included patches: 1-3995

.bashrc 
```
...
export XDG_CONFIG_HOME=$HOME/.config
export SPACEVIMDIR=$XDG_CONFIG_HOME/spacevim.d
alias vim="vim -u $XDG_CONFIG_HOME/spacevim/vimrc"
...
```

[log.txt](https://github.com/SpaceVim/SpaceVim/files/7832618/log.txt)

**Comment by wsdjeg** [comment]
@danchev please following the installation guide. `vim -u ....` will not add the runtimepath automatically for spacevim.

**Comment by Mick235711** [comment]
(Some additional information: `vimdiff`, `view` and `nvim -d` also does not work, so probably some initial settings issue? I'm not sure why only `vim`/`nvim` works.)
