### ISSUE TITLE
[deoplete] omni source does not support: phpcomplete#CompletePHP

### ISSUE THREAD

**Issue by xi4oh4o** [wsdjeg/SpaceVim#563]
## Environment Information
- OS: OS X  Sierra 10.12.5
- vim version:
- neovim version: NVIM 0.2.0

## The reproduce ways from Vim starting (Required!)

1. Open a new file called: test.php:
2. write codes, like below:
````
<?php
$r->
````

3. You can see this
![image](https://cloud.githubusercontent.com/assets/141127/26481538/3db4c072-4214-11e7-80f2-05f51b142244.png)

## Output of the ':SPDebugInfo!'
:SPDebugInfo            ### SpaceVim Options :
````
:SPDebugInfo            ### SpaceVim Options :

```viml
g:spacevim_enable_os_fileformat_icon = 0
g:spacevim_leader_guide_position = 'botright'
g:spacevim_version = '0.3.0-dev'
g:spacevim_force_global_config = 0
g:spacevim_smartcloseignoreft = ['help']
g:spacevim_default_indent = 2
g:spacevim_enable_key_frequency = 0
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_enable_powerline_fonts = 1
g:spacevim_statusline_separator = 'arrow'
g:spacevim_warning_symbol = ' '
g:spacevim_simple_mode = 0
g:spacevim_colorscheme = 'gruvbox'
g:spacevim_enable_guicolors = 1
g:spacevim_custom_plugins = []
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}
g:spacevim_buffer_index_type = 0
g:spacevim_hiddenfileinfo = 1
g:spacevim_enable_vimfiler_gitstatus = 0
g:spacevim_plugin_manager = 'dein'
g:spacevim_error_symbol = ' '
g:spacevim_vim_plug_installed = 0
g:spacevim_windows_leader = 's'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
g:spacevim_use_colorscheme = 1
g:spacevim_colorscheme_bg = 'dark'
g:spacevim_enable_neocomplcache = 0
g:spacevim_leader_guide_sort_horizontal = 0
g:spacevim_enable_vimfiler_welcome = 1
g:spacevim_max_column = 120
g:spacevim_enable_debug = 0
g:spacevim_vim_help_language = 'en'
g:spacevim_lint_on_save = 1
g:spacevim_dein_installed = 1
g:spacevim_autocomplete_method = 'deoplete'
g:spacevim_enable_vimfiler_filetypeicon = 0
g:spacevim_plugin_manager_max_processes = 8
g:spacevim_unite_leader = 'f'
g:spacevim_enable_ycm = 0
g:spacevim_enable_tabline_filetype_icon = 0
g:spacevim_colorscheme_default = 'desert'
g:spacevim_plugin_groups_exclude = []
g:spacevim_neobundle_installed = 0
g:spacevim_disabled_plugins = []
g:spacevim_leader_guide_max_size = 0
g:spacevim_guifont = ''
g:spacevim_plugin_groups = ['web', 'lang', 'edit', 'ui', 'tools', 'checkers', 'format', 'chat', 'git', 'javascript', 'ruby', 'python', 'scala', 'lang#go', 'lang#markdown', 'scm', 'editing', 'indents', 'navigation', 'misc', 'core', 'core#statusline', 'core#tabline', 'default', 'unite', 'github', 'denite', 'ctrlp', 'autocomplete', 'nvim', 'osx', 'colorscheme', 'core#banner']
g:spacevim_leader_guide_flatten = 1
g:spacevim_sidebar_width = 30
g:spacevim_enable_googlesuggest = 0
g:spacevim_language = ''
g:spacevim_enable_neomake = 1
g:spacevim_plugin_bundle_dir = '/Users/xi4oh4o/.cache/vimfiles/'
g:spacevim_leader_guide_run_map_on_popup = 1
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_leader_guide_default_group_name = ''
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_terminal_cursor_shape = 2
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_snippet_engine = 'neosnippet'
g:spacevim_leader_guide_vertical = 0
g:spacevim_enable_cursorcolumn = 0
g:spacevim_realtime_leader_guide = 1
g:spacevim_leader_guide_hspace = 5
g:spacevim_denite_leader = 'F'
g:spacevim_checkinstall = 1
g:spacevim_plugin_name = 'gruvbox'
g:spacevim_enable_cursorline = 1
g:spacevim_lint_on_the_fly = 0
g:spacevim_debug_level = 1
g:spacevim_filemanager = 'vimfiler'
g:spacevim_src_root = 'E:\sources\'
```


### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/0.2.0/bin/nvim)
version: 704
OS: OSX
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :
````
## Screenshots
https://asciinema.org/a/6ne1fvly5edqk6tx612mhrv4v

**Comment by Shougo** [comment]
SpaceVim set `g:deoplete#omni#input_patterns` php configuration.
But phpcomplete is not omni source compatible.
It should be fixed.

**Comment by wsdjeg** [comment]
@xi4oh4o for php file, I think you should load lang#php layer, and we use phpcd.vim for php completion. and you should checkout the doc of this layer.

http://spacevim.org/layers/lang/php/

BTW, If user do not load this layer, phpcomplete will be used, hmm, I will look into that plugin, and try to fix this error.

**Comment by wsdjeg** [comment]
@Shougo why this func is not omni source compatible, it move cursor?

**Comment by xi4oh4o** [comment]
@wsdjeg I load lang#php layer, But still this problem.

My step. 
1. add `call SpaceVim#layers#load('lang#php')` into .SpaceVim.d/init.vim
2. vim test.php and Waiting for installation dependencies
3. write code like `$r->a` but still show below
![image](https://cloud.githubusercontent.com/assets/141127/26517370/c19bf454-42c9-11e7-8653-7c74c7cab981.png)
![image](https://cloud.githubusercontent.com/assets/141127/26517372/c8061900-42c9-11e7-8cbb-d5247196c547.png)





## SPDebugInfo: 
`g:spacevim_plugin_groups = ['web', 'lang', 'edit', 'ui', 'tools', 'checkers', 'format', 'chat', 'git', 'javascript', 'ruby', 'python', 'scala', 'lang#go', 'lang#markdown', 'scm', 'editing', 'indents', 'navigation', 'misc', 'core', 'core#statusline', 'core#tabline', 'default', 'unite', 'github', 'denite', 'ctrlp', 'autocomplete', 'nvim', 'osx', 'colorscheme', 'core#banner', 'lang#php']`

**Comment by wsdjeg** [comment]
please use :SPInstall to install all plugins in layer.

**Comment by Shougo** [comment]
> @Shougo why this func is not omni source compatible, it move cursor?

Yes.

**Comment by wsdjeg** [comment]
hmm, seems a bug, I will fix it, if you load the `lang#php` layer, the omnifunc should be phpcd.

**Comment by wsdjeg** [comment]
I just check it, it works well for me, `echo &omnifunc` is `phpcd#CompletePHP`

here is vedio:

[![asciicast](https://asciinema.org/a/6r6ui2jkmqan7nzc3xa3i4f2f.png)](https://asciinema.org/a/6r6ui2jkmqan7nzc3xa3i4f2f)

**Comment by wsdjeg** [comment]
you need run `composer install` in the root of phpcd.vim, by default SpaceVim should run it when install plugin.
